baseURL = 'https://github.com/ushaimramadhan'
languageCode = 'id-ID'
title = 'Ushaim Ramadhan' 
theme = 'PaperMod'

[params]
    defaultTheme = 'auto'
    author = 'Ushaim Ramadhan'
    ShowReadingTime = true
    
    # Bagian Profile Mode (Halaman depan jadi kartu nama digital)
    [params.profileMode]
    enabled = true
    title = "Ushaim Ramadhan"
    subtitle = "Informatics Student | Cyber Security Enthusiast"
    imageUrl = "https://github.com/ushaimramadhan.png" # Foto profil GitHub otomatis
    imageTitle = "Hi there!"
    imageWidth = 150
    imageHeight = 150

    [[params.socialIcons]]
    name = "github"
    url = "https://github.com/ushaimramadhan"
    [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/ushaimramadhan"
    [[params.socialIcons]]
    name = "email"
    url = "mailto:adhan1005@gmail.com" 

# Menu Navigasi (Supaya ada pemisah jelas)
[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects" # Persiapan masa depan
    url = "/projects/"
    weight = 20